### ISSUE TITLE
NFT is not displayed

### ISSUE THREAD

**Issue by Prof2517** [tonrocket/bug_reports#14]
### Bug Type

Functional

### Reproduction steps

1. Open @TonRocketBot
2. Link a Tonkeeper Wallet
3. Check the NFT balance

### Actual result

NFT is not displayed
![IMG_9033](https://user-images.githubusercontent.com/113227838/192146916-2a645190-5bfb-4826-810b-34a260ac03f6.PNG)

### Expected result

NFT are displayed

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):
- Device: [e.g. iPhone13 Pro Max]
- OS: [e.g. iOS15.3.1]

**Comment by AleksandrShepelev** [comment]
You mean, NFT of our project? You own it?
